name: Auto Merge

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  auto-merge:
    if: ${{ github.head_ref == 'chore/update-nix-fetch-git' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: generate-token
        with:
          app-id: ${{ secrets.CPR_APP_ID }}
          private-key: ${{ secrets.CPR_APP_PRIVATE_KEY }}

      - name: Enable Pull Request Automerge
        run: gh pr merge --squash --auto ${{ github.event.number }}
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
