name: Build

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      verbose:
        description: Enable verbose logging for Nix builds
        required: false
        default: false
        type: boolean

jobs:
  linux:
    runs-on: ubuntu-latest
    env:
      VERBOSE_FLAGS: ${{ inputs.verbose == true && '--verbose --print-build-logs' || '' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Nix
        uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31.11.0
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix build --accept-flake-config .#nixosConfigurations.mothership.config.system.build.toplevel $VERBOSE_FLAGS

  arm-macos:
    runs-on: macos-26
    env:
      VERBOSE_FLAGS: ${{ inputs.verbose == true && '--verbose --print-build-logs' || '' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Nix
        uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31.11.0
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix build --accept-flake-config .#darwinConfigurations.MacBook-Pro-2.config.system.build.toplevel $VERBOSE_FLAGS

      - run: nix build --accept-flake-config .#darwinConfigurations.damascus.config.system.build.toplevel $VERBOSE_FLAGS

      - run: nix build --accept-flake-config .#devShells.aarch64-darwin.mf $VERBOSE_FLAGS
