name: Update flake lock

on:
  workflow_dispatch:
  schedule:
    - cron: "22 9 * * 0"

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      
      - uses: DeterminateSystems/magic-nix-cache-action@main
      
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v20
        with:
          token: ${{ secrets.GH_TOKEN }}
